Repository pyca/cryptography, pull requests merged in 2018-10, with the labels that each got.

#4492 Add definitions that help with hostname checking
  src/_cffi_src/openssl/ssl.py
  src/_cffi_src/openssl/x509_vfy.py
  src/cryptography/hazmat/bindings/openssl/_conditional.py
Labels: bindings

#4524 add _create_asn1_time
  src/cryptography/hazmat/backends/openssl/backend.py
Labels: cleanup

#4532 add bindings for supporting the issuing distribution point CRL extension
  src/_cffi_src/openssl/x509v3.py
Labels: bindings

#4536 refactor _decode_dist_points
  src/cryptography/hazmat/backends/openssl/decode_asn1.py
Labels: cleanup

#4542 create & use _evp_md_from_algorithm and _evp_md_non_null_from_algorithm
  src/cryptography/hazmat/backends/openssl/backend.py
  src/cryptography/hazmat/backends/openssl/hashes.py
  src/cryptography/hazmat/backends/openssl/hmac.py
  src/cryptography/hazmat/backends/openssl/rsa.py
  tests/hazmat/primitives/test_rsa.py
Labels: administrative

#4535 add pkcs12 test vectors
  docs/development/test-vectors.rst
  vectors/cryptography_vectors/pkcs12/cert-key-aes256cbc.p12
  vectors/cryptography_vectors/pkcs12/cert-none-key-none.p12
  vectors/cryptography_vectors/pkcs12/cert-rc2-key-3des.p12
  vectors/cryptography_vectors/x509/custom/ca/ca.pem
  vectors/cryptography_vectors/x509/custom/ca/ca_key.pem
Labels: vectors
