Repository pyca/cryptography, pull requests merged in 2019-04, with the labels that each got.

#4827 Ignore the Russian CA for now
  docs/conf.py
Labels: documentation, testing

#4829 Fix typo
  docs/x509/reference.rst
Labels: documentation

#4831 Added BN_is_negative -- refs #4830
  src/_cffi_src/openssl/bignum.py
Labels: bindings

#4842 Refs #4830 -- added a vector of an x.509 certificate with a negative …
  docs/development/test-vectors.rst
  vectors/cryptography_vectors/x509/custom/negative_serial.pem
Labels: vectors
